// Code generated by generate-ast. DO NOT EDIT.
package ast

import "github.com/michael-go/lox/golox/internal/token"

type Expr interface {
	Accept(visitor Visitor) any
}

type Binary struct {
	Left     Expr
	Operator token.Token
	Right    Expr
}

type Grouping struct {
	Expression Expr
}

type Literal struct {
	Value any
}

type Unary struct {
	Operator token.Token
	Right    Expr
}

type Visitor interface {
	VisitBinaryExpr(expr Binary) any
	VisitGroupingExpr(expr Grouping) any
	VisitLiteralExpr(expr Literal) any
	VisitUnaryExpr(expr Unary) any
}

func (expr Binary) Accept(visitor Visitor) any {
	return visitor.VisitBinaryExpr(expr)
}

func (expr Grouping) Accept(visitor Visitor) any {
	return visitor.VisitGroupingExpr(expr)
}

func (expr Literal) Accept(visitor Visitor) any {
	return visitor.VisitLiteralExpr(expr)
}

func (expr Unary) Accept(visitor Visitor) any {
	return visitor.VisitUnaryExpr(expr)
}
