name: test
on: [push]
jobs:
  test-golox:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: golox
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  test-rslox:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: rslox
    steps:
      - uses: actions/checkout@v3
      - name: install rustfmt
        run: rustup component add rustfmt
      - name: Check fmt
        run: rustfmt --check src/main.rs
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
  test-origin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: run test from origin book repo
        run: make test-origin

